# Generated by Django 5.0.14 on 2025-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="input_source",
            field=models.CharField(
                blank=True,
                choices=[("isbn", "ISBN"), ("ocr", "OCR"), ("manual", "Manual")],
                default="manual",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
