# Generated by Django 5.0.14 on 2025-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0002_alter_book_author_alter_book_input_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
